namespace Bark.Tools
{
    public static class Sounds
    {
        public enum Sound
        {
            None = 0,
            pillowhandtap = 3,
            grassrockhandtap = 7,
            barkhandtap = 8,
            woodhandtap = 9,
            dirthandtap = 14,
            metalhandtap = 18,
            crystalhandtap = 20,
            leafcrunch = 31,
            snowstep = 32,
            crystalhandtap_root_2octdown = 40,
            crystalhandtap_second_2octdown = 41,
            crystalhandtap_third_2octdown = 42,
            crystalhandtap_fifth_2octdown = 43,
            crystalhandtap_sixth_2octdown = 44,
            crystalhandtap_root_1octdown = 45,
            crystalhandtap_second_1octdown = 46,
            crystalhandtap_third_1octdown = 47,
            crystalhandtap_fifth_1octdown = 48,
            crystalhandtap_sixth_1octdown = 49,
            crystalhandtap_root = 50,
            crystalhandtap_root_second = 51,
            crystalhandtap_third = 52,
            crystalhandtap_fifth = 53,
            crystalhandtap_sixth = 54,
            umbrellaopen = 64,
            umbrellaclose = 65,
            keyboardclick = 66,
            buttonpress = 67,
            p2_racktom = 68,
            p1_snare = 69,
            p2_floor_tom_2 = 70,
            p2_kick = 71,
            p1_open_hat = 72,
            bongolowest = 73,
            bongohigh = 74,
            squeak_squeeze = 75,
            squeak_release = 76,
            bonerattle = 77,
            Tombstone_Surface_04 = 78,
            cauldroninner = 79,
            Cauldron_Surface_04 = 80,
            pumpkinhit = 81,
            Web_Surface_02 = 82,
            ShortTurkeyGobbleBQuiet = 83,
            foodpop = 84,
            bite1 = 85,
            bite2 = 86,
            bite3 = 87,
            HayImpactA = 88,
            ropecreak = 89,
            planthit = 90,
            ToyFrogSound = 91,
            VineHit1 = 92,
            cloud2 = 93,
            woodfloor2 = 94,
            tire = 95,
            fruitsquish1 = 96,
            washingmachinehit = 98,
            LeafHit1 = 99,
            skyjunglewood2 = 100,
            skyjunglewood = 101,
            huthit = 105,
            fireflyjarhit = 106,
            beanbag1 = 107,
            beanbag2 = 108,
            softhit1 = 110,
            storewoodhit = 112,
            shelfhit = 114,
            roofhit = 115,
            cranehit = 116,
            rughit1 = 118,
            snowglobehit = 120,
            ornamenthit = 121,
            gifthit = 134,
            ToyGorillaElf_Squeeze = 140,
            ToyGorillaElf_Release = 141,
            metalhit1 = 146,
            metalhit2 = 149,
            PenguinSqueeze = 154,
            PenguinRelease = 155,
            WolfSqueeze = 156,
            WolfRelease = 157,
            BoxHit = 160,
            DungeonPillowHit = 164,
            BasementWoodWall = 173,
            BookHit = 178,
            MonkeyeSqueeze = 187,
            DragonSqueeze = 188,
            ConcreteHit = 189,
            BeeSqueeze = 191,
            SpongeSquish = 193,
            SpongeRelease = 194,
            CoyoteHowl_Quiet2 = 195,
            DivingBoardBounce = 196,
            SandTap = 197,
            PalmTreeBark = 198,
            SharkSqueeze = 200,
            SharkRelease = 201,
            TentBounce = 202,
        }
        public static void Play(int sound, float volume = 0.1f, bool isLeft=false)
        {
            GorillaTagger.Instance.offlineVRRig.PlayHandTapLocal(sound, isLeft, volume);
        }

        public static void Play(Sound sound, float volume = 0.1f, bool isLeft = false)
        {
            GorillaTagger.Instance.offlineVRRig.PlayHandTapLocal((int)sound, isLeft, volume);
        }
    }
}
